env:
  browser: true
  es6: true
  jquery: true
extends: 'eslint:recommended'
rules:
  indent:
    - warn
    - 4
  linebreak-style:
    - warn
    - windows
  quotes:
    - warn
    - double
  semi:
    - warn
    - always
